### ISSUE TITLE
Browser Spell Check in upcoming Markdown editor

### ISSUE THREAD

**Issue by ghost** [typemill/typemill#10]
Hello Developers,

First and foremost my praise for the new admin dashboard on the Typemill Flat File CMS. I saw it today on Github and set everything up right away. Also should be mentioned in the tutorials for the update, that you have to make the composer update. Otherwise, the website is not accessible.

In addition, you can not rename the default settings file, because otherwise you can create under `/setup` no new user and it is equal to the login mask. But I found out everything :-)

My question would still be: Will there be a browser spellchecker in the new Markdown Editor, which is important for German users like me, for example.

That would be my suggestion and I'm looking forward to the next Typemill releases. Thank you all.

**Comment by trendschau** [comment]
Hi Alex, 

thank you very much for the feedback, I will update the documentation with the next release. 

Regarding the spellchecker: This is not planned in near future because the whole content editor and media management will already be quite a lot of work in its basic form. But a spell checker might be a good candidate for a plugin in future.

Best regards, Sebastian

**Comment by AlexL777** [comment]
Hi,
Thanks for your info and a Spell Checker plugin would be really good, I think.

Then I wait until it's done with the plugin and your CMS I like to use. Thank you.

**Comment by trendschau** [comment]
v2 is out now and spell checks will be done with a planned plugin in future.
