### ISSUE TITLE
Using HTML inline

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#109]
Proposition closed. Finis.

**Comment by trendschau** [comment]
Sorry, not sure what you mean exactly. The theme's custom css-field is for css only, of course. Do you mean the content-area with the raw markdown mode?

The library is capable of html as it is specified by markdown. But in Typemill this feature is turned off because of security concerns. To enable html in markdown editor, I have to do a lot of sanitizing.

There was a discussion about it in issue #83 already.

I have it on my list, together with a div-component for content to create custom elements. But both is low prio. Usually you should do all the html-markup and coding in the theme-files, not in the content area. As a dirty solution I could implement a html-on-settings without sanitizing it, but I would add that only in the yaml-file, not in the admin-ui, so people who use it know what they do.

**Comment by DialogusOne** [comment]
Thanks for responding quickly. 
In the content area I would like to use html classes on the fly as the markdown seems not to support identation (typografical issue), centered, colouring of words or phrases, for example. This is sometimes essential for book pages. 
Any chances to solve this?

**Comment by trendschau** [comment]
Yes, that is indeed not supported by Markdown, there are other markup-languages like textile or restructuredText (?) that support formattings like that.

Typemill uses the [safe mode for parsedown](https://github.com/erusev/parsedown#security). There are [two places in the code](https://github.com/typemill/typemill/search?q=setSafeMode&unscoped_q=setSafeMode) where it is activated. You can try to uncomment them as a quick workaround, but I am not sure if there are other places where html-input is checked again. 

I can have a look into it for the next release and if it is easy, I can add a yaml-setting like described as a dirty and unsecure solution. I do not want to integrate html in the core of Typemill because you need an extra library like htmlpurifier to make it secure. This adds a lot of code and complexity that I do not want. 

Maybe I can change the code in a way that someone can create a plugin to add htmlpurification for people who need that.

**Comment by timwasson** [comment]
Plus one to allow HTML inside content written in Typemill, whether that is allowed via yml or a setting in the UI, it'd allow a lot more advanced flexibility in editing content.

**Comment by trendschau** [comment]
there is/was a html open/close plugin for typemill. I will think about a simple way to add tags in a different way. As I said, security concerns are more important and htmlpurifier is simply too big to add it to the core of Typemill. Not on my roadmap right now but contributions or plugins are welcome.
