### ISSUE TITLE
Expected behavior of video in editor?

### ISSUE THREAD

**Issue by timwasson** [typemill/typemill#115]
When I try to insert an YouTube video into the editor, nothing seems to happen at all. What is the expected behavior here? Is there a recommended approach to YouTube or other embedded videos in the content? I am going to try using custom classes and IDs on images, along with a Javascript approach for videos (ie, https://www.sitepoint.com/faster-youtube-embeds-javascript/), but I'd prefer to use native functionality of Typemill if it exists.

**Comment by trendschau** [comment]
Hi Tim, the expected behavior is that it fetches the preview-image of the video from youtube and displays it together with a play button. If user clicks on the play button, the youtube image is loaded and starts immediately. For the website itself it needs a bit of javascript that is part of the typemillUtilities. 

I just tested it and there is a bug, probably caused by the last release where I completely refactored the image management. Looks like I forgot the youtube part. 

I will fix it with the next release. 

Thank you for reporting.

**Comment by trendschau** [comment]
refactored for version 1.3.5. Video will always open in the video-component, not in the image component in future. Removed youtube and vimeo-classes from image component.

**Comment by trendschau** [comment]
published with version 1.3.5 today.
