### ISSUE TITLE
Add a class to paragraphs with only images

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#130]
I'm looking for a way to style the first image in a document. I think it would be usefill that Typemill will detect paragraphs that only contain an image and adds a class like "figure" to it.  So I'm more flexible to style a header image and its container. Because every Image is inside a paragraph the CSS selector `img:first-child {}` does not help in the current implementation.

**Comment by trendschau** [comment]
good idea, that might also help with the styling of the caption. I will have a look into it.

**Comment by trendschau** [comment]
paragraphs with images get the class "p-image" as of version 1.3.6

**Comment by trendschau** [comment]
I dropped this solution because it did not resolve some design issues with captions. 

Images in a separate line are now rendered with html5-tag "figure" and "figcaption", so you can try to use the first-child-selector with figure.

There is also a hero-image now that you can use for ... hero images on a page.
