### ISSUE TITLE
Plugin Analytics »Matomo«

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#143]
The plugin seems not to work properly, it shows no resuslts, counters etc.  

Your code on each typemill web page differs from the current Matomo code:

  
<script type="text/javascript">  
  var _paq = window._paq || [];  
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */  
  _paq.push(['trackPageView']);  
  _paq.push(['enableLinkTracking']);  
  (function() {  
    var u="https://»URL«/matomo/";  
    _paq.push(['setTrackerUrl', u+'piwik.php']);  
    _paq.push(['setSiteId', '»Site ID«']);  
    var d=document, g=d.createElement('script'),   s=d.getElementsByTagName('script')[0];  
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);  
  })();  
</script>  
  

The backlink reads https://»insert server URL«/matomo/

Perhaps you could look into it.

**Comment by trendschau** [comment]
You can insert the link to your matomo-installation into the plugin, so this is not the reason. 

The reason is probably that matomo changed the naming of the files in the latest versions, so `_paq.push(['setTrackerUrl', u+'piwik.php']);` is now `_paq.push(['setTrackerUrl', u+'matomo.php']);` and `g.src=u+'piwik.js';` is now probably `g.src=u+'matomo.js';`. 

I will have a look into it when I find time, I have to find time to update my own matomo installation (which is quite a pain) and create a separate plugin-version for new installations.

**Comment by trendschau** [comment]
I updated the plugin yesterday so it works now with latest matomo-versions.
