### ISSUE TITLE
1.3.6 — Mismatch of Meta Navigation Title and Cover Page Titles

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#148]
I use the special start design cover page. The display list of all pages show capitalized page names, e.g. »Autor Und Leser«, although the meta navigation titles reads »Autor und Leser«.

**Comment by trendschau** [comment]
That is caused by this css-lines: 

`
.toc-nav li {
    text-transform: capitalize;
    text-align: left;
}
`
you can change it in your custom css to:

`
.toc-nav li {
    text-transform: none;
    text-align: left;
}
`

I can fix it for the next release. BTW I will probably drop that standard theme in near future and not support it anymore because the code is more than 3 years old and hard to maintain. Anyway, the theme stays available of course...

**Comment by trendschau** [comment]
this should work now with version version 1.2.6 of the theme: https://themes.typemill.net/typemill
