### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by AndiLeni** [typemill/typemill#15]
Hello.
I've been following Typemill for a while now. The way this CMS is changing is great. 
But in my opinion it would be a pity if such a good CMS would only be used for documentation and stuff like that. I know that's the way you want it to be. But please remember: The only other CMS that allows such a free definition of forms is KirbyCMS, which is commercial. Typemill would be a good open source approach to close this gap. 
I also don't demand that the form (for documentation) be neglected, but a few more features to be able to use it for regular websites would be great! For example, the ability to create multiple designs and then select which design to use in the editor. (If this is already possible I apologize and would like to know how to do this :)   ).

Regards 
Andi

**Comment by trendschau** [comment]
Hi Andi, 

thank you very much for that feedback, I am happy that some people take notice of this small project!

Yes, I plan to make the system a bit more flexible in future with a template-selection that you mentioned and some more features, so that you can also realize more general website concepts with typemill. This requires meta-information for pages. I plan to implement this after I have finished the wysiwyg-editing mode.

Like you said, I am still not sure how far to go in this direction (general website cms). There are so many good and mature options out there even in the space of flat file systems: Kirby and Statamic or Open Source Systems like Grav, Bludit, BatFlat, Automad and many more. Not sure if Typemill has a real usp in this space ... 

The main goal for typemill is to create a small publishing system with a single source publishing based on files, some options to create ebook-formats on the fly and maybe even options to distribute and sell the text-work in the background. I don't see really good solutions for publishers and writers right now and I know that some of them are waiting for it. But it is allways hard to decide which way to go and keep on the path ... :D 

The template selection will take some time because the wysiwyg editing is pretty complex, so not before the end of the year, I think ...

**Comment by trendschau** [comment]
Hi Andi, 

I will close this ticket because Typemill has evolved within the last 2 years and you can build much more than documentation sites with it now.
