### ISSUE TITLE
Is the standard theme Typemill a dead end?

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#150]
Recently you said https://github.com/typemill/typemill/issues/148#issuecomment-625702204: »I will probably drop that standard theme in near future and not support it anymore because the code is more than 3 years old and hard to maintain.« 

Of course, you are not commited to continue a solution indefinitely. But as the target group you are aiming at are authors, working not just on short time projects, there should be a perspective. Will there be a suitable replacement, so that contents can be used further on? 

As I have just started using Typemill intensively, your comment involves a vital decision whether to continue or look for an alternative. Some more thoughts would be appreciated.

**Comment by trendschau** [comment]
Sorry for confusion: The theme "typemill" will stay online of course and I will proceed to fix real bugs in future. At the same time I will create a new standard theme with a fresh code and ship that as the new standard theme. 

You can of course use the recent standard theme in future, too, and it works fine as you see, but I will not make any enhancements or refinements or support when it is replaced. This is the same procedure as every cms does, WordPress replaces the standard theme nearly every year ...

**Comment by DialogusOne** [comment]
I write as an author of nonfiction books. The following therefore elaborates on my personal perspective, which upfront concludes to: Yes, the current standard theme is a dead end. This is not meant to be a critique, but rather a bunch of thoughts and notices to improve next Typemill’s standard theme. 

First of all, Typemill should make it clear what type of authors (see https://github.com/typemill/typemill/issues/80) it aims at. There are certainly huge differences between authors of code or documentation, technical books, literature or bloggers on everyday life subjects. If the roadmap suggests a »fully featured publishing system«, then Typemill should also concentrate on concrete publishing needs. Of course, one system does not fit all. 

Here are my collected reasons.

- The workflow of authoring is in somehow tiresome. Although the applied markdown editors are easy for writing offhand or for quick-and-dirty blog entries, they still lack essential elements for composing sophisticated books/articles, e.g. centered text, paragraph indentation, subscript or superscript, using specific fonts for certain tasks (see CMS  »Typesetter«).  
- The typographics are rudimentary. This could be overcome by using html inside, which, alas, is not supported by Typemill. Opening up the system there would enhance the productive side immensely. 
- I am using »PhraseExpress«, a tool to avoid repetetive writing tasks, like wordings, formulas, even html code. However, this interferes negatively with the visual editor as each »return/enter« closes the active block and opens another, which is in this instance not intended. The latter can be overcome in using the raw mode, but then other problems occur (see https://github.com/typemill/typemill/issues/155).
- One major shortcoming reflects the title’s limitation to 60 characters. This is just insufficient to represent a meaningful statement or an attractive title. Looking at the sitemap, which is one of the basis for SEO etc., it delivers the same shorthand, cryptographic style, which in turn does not hint the content or may hit search criteria. 
- Working with many pages (e.g. chapters, sub-chapters, sections) the navigation menu quickly gets crowded. It may be useful to make the nav menu static/sticky (viewport Desktop) or to implement a short cut, so that scrolling up and down larger entries can be avoided and a redirection to other subject pages is available all the time. 

Just my 2 cents.

**Comment by trendschau** [comment]
thanks for your feedback. 

Some points: 

* All that you say is simply not defined by standard markdown. Secondly this is partly a task of the theme and you can code your own theme if you want. 
* This is part of a theme and you can code your own theme with any font you want. 
* I don't know that software and typemill works like it works. I run several very successful websites with it, so I don't see any problem. 
* It makes no sense to accuse 60 characters limitations and point to SEO because less than 60 characters are exactly the recommended size for SEO / Google titles. However, Typemill is super great for SEO.
* That is again part of the theme and everybody can code it like he wants for his project. That is the nature of CMS software.

To be honest, I am a little bit tired of feedback that only reflects personal preferences. Typemill is an open source project, I provide everything for free and the support I provide here (costfree) is huge and much more than is healthy for me. You can always use another software, so if Typesetter fits better to your need, then that is fine ....

**Comment by trendschau** [comment]
Just to clarify once more: The sitemap for example is a google sitemap (as the field label says) and it follows the google standard. If you are not familiar with SEO in depth than that is totally fine, but I will close comments like this because other users without SEO knowledge will get a completely wrong impression.
