### ISSUE TITLE
Edit link to backend

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#183]
Hi,

is it possible to add a link for example in the footer which directs me to the backend where I can edit the particular page?

**Comment by trendschau** [comment]
Not so easy because typemill does not use sessions in frontend by default. You could problably create a plugin that starts session on all frontend pages. Then you can make use of the twig-function is_role('administrator') and conditionally add the link. The link is always the same: base_url() + tm/content/visual (or raw if you prefer raw mode) + $item->urlRel. 

If it is fine to show the link to everyone in frontend, then you can do it without session. Users that are not logged will be redirected to the login page then. So something like that in footer: 

`<a href="{{ base_url() ~ '/tm/content/visual' ~ item.urlRelWoF }}">edit</a>`

**Comment by Tekl** [comment]
Uh, thanks, that works well.
