### ISSUE TITLE
Feature Request: Hide from page list

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#188]
As the 'hide from navigation' meta option does not hide a sub-page from a page list, there needs to be an option to hide also there. 

I want to prepare a page which should not be visible to visitors until it is finished. I can't take it offline as I already need the URL for testing in other cases.

**Comment by trendschau** [comment]
not totally sure if I understand it correctly, so if you hide a folder, then it does not hide the content-pages inside that folder (sub-pages)? Or is the page not hidden from certain navigations on the page? The hide-feature turned out to be very complex in the background, so I want to avoid changing it too much. 

By the way, I work on a pro-content-Feature where content is only accessible for certain user-roles like "members". This might be a solution for your problem and will probably be published with the next release.

**Comment by Tekl** [comment]
Maybe I did something wrong. I tried to reproduce it and now the article does not appear in the page list. So it already works like expected. Sorry for opening this issue.
