### ISSUE TITLE
Make it impossible to loose data with visual editor

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#189]
Currently the visual editor has a big problem that drive me nuts:

Here what very often happens in my case:

1. I edit a paragraph, a table or something else
2. I want to copy a phrase from another paragraph or table and click there to select the text
3. The first visual editor will be cancelled and all edits are lost and now the visual editor of the clicked element is openend

There could be different solutions to avoid this:

1. Leave multiple visual editors open for unsaved/uncanceled content blocks
2. When the content in a visual editor is edited, lock the editor so that I have to click on save/cancel first before editing another section.
3. Just treat leaving the editor block as save
4. Ask the user what to do, when he leaves a editor without saving/canceling

**Comment by trendschau** [comment]
I will investigate it. Vue has the option to keep the data for forms, but it will interfer with the Typemill logic. I suppose the best way is to store changes automatically if block closes and editor did not click the "cancel" button.

**Comment by trendschau** [comment]
Solution 2 is implemented in next release 1.4.0: When the content block is edited in the visual mode, then the editor is locked so that you have to click on save/cancel first before editing another section.

Automatic saving is another option, but I am not sure if all users want that behavior in all situations (you can't cancel and go back to the previous version then). 

The downside of the current solution (lock editor) is, that you cannot open another block to copy the markdown. Anyway, in the visual editor the complex markdown (images, tables and similar) is not directly visible, so the use of copy and paste is very limited.

**Comment by trendschau** [comment]
published with version 1.4.0
