### ISSUE TITLE
A way to use TM without the base tag in a theme?

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#202]
I want to use a some anchor links im my documents, but they don't work if I just use relative anchors like: `<a href="#anchor">Link</a>`

When I remove the base tag from the theme, the images will not load anymore as they are relative. 

I don't understand why it works this way, but I think there should be an option to place images with absolute links. If here's a good reason to not change this, there could be an automatism that adds the full url to relative anchors.

**Comment by trendschau** [comment]
For Anchors you can use the relative URL starting with the base-url like /mypage/mysubpage#anchor. I can try to enhance the link-editor some day, so it automatically adds the url of the page for anchors. 

I don't want to change the basic logic because it is needed for image linking. If you add absolute images, then you cannot move your Typemill installation from one place to another or change your domain easily and that is one big advantage of Typemill: You can create your whole website on localhost, move it to a server and everything will work without problems...

**Comment by Tekl** [comment]
An enhancement for the link-editor could be a good compromise, but better would be in my opinion a server side process that adds the absolute urls to the anchor in the rendering process.

I understand that moving a website as easy as possible is very important. But this should also be respected for anchors. Currently I have to adopt my markdown texts from other sources/editors to work with Typemill and when I copy/move content to another place inside Typemill, I'll have to edit all anchors.

There's also a usability issue as most people won't think that on-page-anchors should include a path. It took me some time to understand, why they don't work in Typemill but everywhere else.

**Comment by trendschau** [comment]
I agree that it is not optimal right now. Next problem will be the link and image handling for epub export. I will keep that in mind and look when I find time for it, I suppose it might become complicated, breaking change for existing content and a lot of rewriting in the markdown -> html conversion process...

**Comment by trendschau** [comment]
Base tag has been removed in version 1.4.0. This is a breaking change, so you have to update your individual themes accordingly.
