### ISSUE TITLE
Special markup or classes to style elements or words

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#208]
I would like to have a bullet list with green ⊕ and red ⊖ symbols and I'm thinking, how this can be achieved within Typemill. As HTML tags are not allowed I can't just add `<span class="plus">⊕</span>` to the text. So a special markup could be a solution. Can the markup be extended by a plugin? If yes, a template plugin would be fine for us script kiddies with less coding experience. ;-)

In some cases Typemill already allows to specify classes by adding `{.className}`. It would be great if this can be extended to Headline, Lists, Paragraphs etc.

And for the span element it would be neat to have the highlight markup of some markdown flavours: 
`normal text ==Text Marker== normal text`. 

This could be transformed into
`normal text <mark class="highlight-text-marker">Text Marker</mark> normal text`  

Well, as this abuse of the mark element could be a semantically problem it could be better to invent a new markup that just generates a span with its content as class name:

`markup to ::surround:: words with span`

→`markup to <span class="span-surround" role="presentation">surround</span> words with span`

**Comment by trendschau** [comment]
thank you for the suggestion! Once again I see the point of such div and span and html-extensions, but right now I have nearly no time for typemill, so I cannot work on features like that in near future. All these special cases are not supported by regular markdown so you have to extend the markdown-syntax which is not trivial. There are a lot of options to extend the language but the problem is that the syntax is probably not supported elsewhere. You can check python markdown, kramdown, pandoc, restructuredText, or maybe it is also an idea to allow only a very basic html syntax with div and span, so that it works everywhere. If I have more time again (maybe next year) I will have a look into it....

**Comment by trendschau** [comment]
Reading this again: I thought the new shortcode-option of version 1.5.1 might help but it probably won't help here. 

But there is a simple way to add some kind of template-logic to a theme. You can add a new select-box in the metatabs with the yaml-file of your theme like this: 

```
metatabs:
  meta:
    fields:
      templates:
        type: select
        label: Select a template
        options:
          templatea: Template A
          templateb: Template B
``` 
Then you can either use that value as a class in your theme or you can try to load different twig-layouts depending on the template value. I did not try it but that would be a pretty easy way to create a page with different list-stylings, for example. Example described in the documentation here: https://typemill.net/forms/meta-tabs

**Comment by trendschau** [comment]
will think about solutions for html later again, but it is not in the focus right now. Anyway, thank you for the suggestions, I will review all possibilities when I implement a simple feature for html-tags.
