### ISSUE TITLE
Footnotes and image size

### ISSUE THREAD

**Issue by carstenwm** [typemill/typemill#21]
Jumped to 1.2.9, love it!
1) Footnotes: jumping to front page (on yours and my own pages)
2) Now that one can't use HTML for img size syntax, any other way?

**Comment by trendschau** [comment]
Glad to hear that!

1. Yes, it is a bug, I will try to fix it with next version.
2. The markdown extra spec shows a way to add those attributes but unfortunately the parsedown-library does not implement it. I will have a look if I can extend the library for that or if I can find another workaround for it.

**Comment by trendschau** [comment]
Both is fixed/added in version 1.2.10.

1. Footnotes work again, but it is not possible to edit footnotes in the visual mode right now, I will add that in version 1.2.11 or 1.2.12
2. You can add attributes like width for images now. I did not add this feature to the visual mode (it is a bit tricky because of responsive behavior), but you can add the width attribute in raw mode like this : `![alt text](link/to/image.png){width=100px}`.

**Comment by carstenwm** [comment]
Oh, nice, and it works with % as well

And footnotes is back on its feet again, thank you, Sebastian

I hesitated to get the admin - raw mode edition of Typemill, I stayed with the 1.1.7 until right after Sylvester, but I must say that it performs very good. I'm using either raw mode or edit on the computer
