### ISSUE TITLE
Menu in Reverse post order

### ISSUE THREAD

**Issue by carstenwm** [typemill/typemill#24]
..Would love to be able to reverse order of the files in the automatic generating of the menu (both 1-10 and 10-1) - since I'm using Typemill for posting Diary-notes (using the dates) with the newest on top on one of my Typemill pages :-)

**Comment by trendschau** [comment]
Hi Carsten, yes, that is already planned (timeless and timebased posts), but it will take some time because I have to create meta-information for entries first. Hopefully I will finish all until June... :)

**Comment by carstenwm** [comment]
Oh, that's what it's called ;-) Sounds good, thank you. I'm looking forward to it - thank you for the fast reply

**Comment by svanlaere** [comment]
Any news on this? Its a feature many are waiting for. Thanks.

**Comment by trendschau** [comment]
I had another project for some month, but recently started to work on Typemill again. The roadmap looks like this: 

* Finish the visual editor (inline elements), until end of 2019
* Add meta-data to pages, which will also allow to sort pages and create blog-like websites, released as version 1.3.X within 1. quarter of 2020

Next (small) release will be published this week. Unfortunately development is a bit slow, but to speed up it needs contributors ...

**Comment by carstenwm** [comment]
Menu: is it possible to collapse or hide some chapters of the Menu in any way - I have some Appendix chapters etc - no one needs to see the files on the page in daily use, but they are nice to have for reference

**Comment by trendschau** [comment]
Hi Carsten, 

I have to think about it. It is likely possible with the planned metadata and maybe a good feature for a plugin. I will start with the metadata (version 1.3.X) probably next week and it will take some weeks to finish. I will create a new issue for it...

**Comment by trendschau** [comment]
With version 1.3.2 the author can hide a page from the main-navigation in frontend #44 with a checkbox in the meta-tab.

Right now the page is only hidden from the main-navigation but it is still present in the paging and the sub-navigation. I will enhance that in a future release.

**Comment by trendschau** [comment]
Regarding the menu in revers post order: 

I plan to do something like this in version 1.3.4 or 1.3.5. But be aware, that typemill will not transform to a traditional blog software, it is simply not made for that.

There are many open questions to this feature, the plan right now is:

* Add a selectbox to FOLDERS where you can choose the sorting of the subpages in that folder.
* Options could be:
** Standard (like it is now)
** Publish Date descending (like a blog)
** Publish Date ascending (probably useless)
* If you select an order like publish date, then
** The prefix of the files will change from 01-name.md to 20200101-name.md
** The files will be hidden from the navigation in the editor-view
** Instead the entries are listed on the content-page below the folder-content.
** Below the folder content there will also be a button to create a new entry.

The concept might change because I am not sure about the pitfalls of this feature. For example: if you change the order of a folder with existing files, then typemill has to rename all files with the correct prefix.

But once again, I won't create a super sophisticated blog-feature because Typemill is created for document- and book-style webpages, the primary goal is to create e-books from typemill-websites on the fly by the end of this year.

**Comment by carstenwm** [comment]
Not a "_traditional blog software, it is simply not made for that_" - No, I know. And that's not what I needed, there's plenty of other systems for Blog's - what you intend seems perfect, Sebastian

**Comment by trendschau** [comment]
small preview of next release 

![blog](https://user-images.githubusercontent.com/2714547/75109553-af6a1d80-5624-11ea-906b-c1dca246ddd4.gif)

**Comment by trendschau** [comment]
Published today with version 1.3.3

As discussed it is not a menu in revers order, but a kind of blog- or new-section that can be created inside a folder.

You need a theme that supports this feature, the standard theme does not support it for now. It is also possible to create a theme that lists the posts of the folder in the startpage, maybe someone has time to create a special blog-theme for typemill...
