### ISSUE TITLE
Pages set as *hidden* from navigation are still showing in sitemap.xml

### ISSUE THREAD

**Issue by thecenters** [typemill/typemill#246]

**Comment by trendschau** [comment]
Yes, the page is only hidden from navigation, but it is still in the sitemap. These functions should not be combined because each user would expect a different behavior. 

Anyway, the feature to hide a page from sitemap is missing right now. It would make sense to combine it with a no-follow attribute for a page, for example. But I have a lack of time right now, so I cannot implement it quickly. Will add this to the roadmap...

**Comment by trendschau** [comment]
Version 1.5.1 has a no-index-checkbox in the meta-tab. This excludes a page from the sitemap. Hidden pages are still included in the sitemap and only excluded from the navigation-elements.
