### ISSUE TITLE
ID-10T  = user error ?

### ISSUE THREAD

**Issue by carstenwm** [typemill/typemill#25]
Do you have any idea as to why it looks like this ?

I've asked the webhost after checking Mod_rewrite, .htaccess  and php Version is okay - they can't help:

http://typemill-nyeste.bork.one/

It's no problem on the older versions of Typemill..

I'm shure it's not the Typemill :-) But then what ? New webhost ? ( gigahost.dk ) or is it as I fear a ID-10T error ?

/Carsten
(I'll delete this later if there's no 'learning' from it..)

**Comment by trendschau** [comment]
Hi Carsten, 

sorry for the late answer, can you explain the problem a bit more? I can see that the CSS is not loaded because the access of the folder is forbidden: http://typemill-nyeste.bork.one/themes/typemill/css/style.css but I cannot find the mentioned error "ID-10T = user error" anywhere.

**Comment by trendschau** [comment]
Hi Carsten, 

I had to google  ID-10T first :D 

You said that you changed the hoster, correct? Can you make sure that you use the latest Version 1.2.15 of Typemill? Because in previous versions there was a bug that stored the absolute folder path in the settings, which means that the application looks to a wrong folder on the new server. 

So please try two steps: 

* Update your version to 1.2.15 if you use an older version and refresh the page with F12 and look if it works. 
* If it does not work after an upgrade, then please backup your old settings file (in settings folder), delete the settings-file and setup the system again. 

If you already use Version 1.2.15, then make sure that you added Typemill in the correct folder of your hoster (they usually have a dedicated public folder for applications). If that does not help either, then ask your hoster about the usual access rights for the folders so that the application can read the htaccess-file. 

Your website responds with a 403 access denied to all theme-files (css/js/png): 

> You don't have permission to access /themes/typemill/css/fontello/css/fontello.css on this server.
> Server unable to read htaccess file, denying access to be safe

Your hoster should be able to tell you which permission rights you have to set.

Hope this helps!!

**Comment by carstenwm** [comment]
Sorry, too much work - thank you for your answers - I'm on it, it's 1.2.15 and I'm in contact with the 'Hoster' (I'm thinking of going on to a new one, have been there >10 years, it's good to make shifts once in a while and start over (for me at least)..

Sorry for leetspeak and self-irony ;-)
/Carsten

**Comment by carstenwm** [comment]
I've been trying two host's, both okay on Mod_rewrite, .htaccess and php Version - now I've uploaded the three versions of typemill I have with me, 1.2.15 - 1.2.10 and 1.1.7 (I think it is), I'll stick with 1.2.10

I still think it's an ID-10T error, something I don't quite get, sorry - but I'll go with 1.2.10 for the time being - especially since I'm not using the backend very much (I'm prefer uploading content via ftp since I can work with my stuff on some no nonse Markdown editor in a bigger 'window' instead of a 'formular size' one)

Works:
http://1210.bork.one/
Doesn't work:
http://1215.bork.one/
http://117.bork.one/

/Carsten

**Comment by trendschau** [comment]
Hi Carsten, 

your server responds with 404 - not found now. So it is an improvement :D But it is super hard to find the reason from outside. If 1.1.7 and 1.2.15 do not work (and show the same error) while 1.2.10 works, then it is even more strange. Can you check your settings.yaml-files if there are some absolute path in it, something like "themeFolder: /x/y/z" ? I will try to investigate later...

Thank you
Sebastian

**Comment by trendschau** [comment]
Or you could check the error.log-files of your hoster and post them here, maybe we can find something in there...

**Comment by carstenwm** [comment]
You can't see the pages? I'll check you response later - btw you can get the ftp access if you want, I don't mind, but you shouldn't use that much energy if it's not your product that fails, Sebastian

**Comment by carstenwm** [comment]
Damn, it *was* a user error - in the upload of the files of the 1.2.15 - no excuses and nothing to learn from it (except for me: total focus)

It works, I love the backend - the large field for the text (that's where I usually pull out and go for the ftp upload of text files instead) and the Markdown possibilities. Thank you!

(Btw I tried to transfer a little € via Paypall but it wasn't possible?)

**Comment by trendschau** [comment]
Hi Carsten, glad to hear that you could solve the problems! Yes, the mobile version is not optimal right now, when I have time I will try to improve in one of the next versions. Donation should be possible via paypall, and always highly welcome :) 

Thank you, I will close this ticket for now.

**Comment by carstenwm** [comment]
I'll try again, the money was returned from PayPal: "Sebastian Schürmannss præferencer for betalingsmodtagelse er indstillet til manuel godkendelse eller afvisning af denne type betaling." (sorry, in Danish, don't know how to translate it)
