### ISSUE TITLE
Feature Request: Columns

### ISSUE THREAD

**Issue by JSG01** [typemill/typemill#29]
Hey there,
i want to aks, if there is a way to implement colums like in the Gutenberg Editor in Wordpress.

I know there is the table-function, but i would like to put an image on the left and a textfield on the right, for example. That would be a nice feature for me.

**Comment by trendschau** [comment]
You can position an image to the center, to the left and to the right floating the text. It is not possible to create colums, because this feature is not supported by markdown. Different Designs are generally possible with a customized theme, I created a two column layout for my private website for example (http://trendschau.net). But this is a task for a developer. 

Generally the design options of Typemill are limited for now. I plan to add more options in future, but Typemill will keep its focus on content

**Comment by JSG01** [comment]
Thanks for your fast response. I will try to use the floating option, this is a good hint. Unfortunately i don't have time to create a whole theme :D but i could make some css changes indeed.

**Comment by trendschau** [comment]
Sounds good. I wanted to add an option for custom CSS for themes, but not sure when I find the time to implement. Hope it works with floating for now. ...
