### ISSUE TITLE
Suggestion: Admonitions - Collapsible blocks

### ISSUE THREAD

**Issue by cjdduarte** [typemill/typemill#303]
I would like to suggest if it is possible to include some Admonitions notation with Collapsible blocks

![Screenshot_1](https://user-images.githubusercontent.com/42243532/154803766-814ba6fb-ff96-408b-a9bf-61b576856eb2.jpg)

https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks

**Comment by trendschau** [comment]
Thank you for the suggestion! 

I think that is a task for a theme developer. You can design collapsable notes in the theme for some or for all admonitions. 

It is not possible to integrate features like that in typemill core because typemill uses a different syntax for admonitions and that syntax does not support classes. You can see the discussion about the syntax here: https://github.com/typemill/typemill/issues/33

**Comment by cjdduarte** [comment]
I solved with theme
