### ISSUE TITLE
Prevent block from accidentally being deleted

### ISSUE THREAD

**Issue by HJB1972** [typemill/typemill#307]
Is there any way to prevent a block from being accidentally deleted. Can a delete warning be implemented "Are you sure you want this block to be deleted?" It is very easy to delete a content block and loose valuable information whilst editing a page. There is currently zero warning unless I am missing something.

**Comment by trendschau** [comment]
Thank you for this suggestion. I have to think about it, because it slows down the edit process and I am not aware of such security questions in other block editors (but I might be wrong). However, there is much space for improvements here: 

* The delete button is way to close to the add-button, this should be improved in future somehow
* You could think about an optional setting where the button changes to to a confirmation button-like "really" so you can double click quickly to finally delete it and avoid an extra overlay. Will add it to the list of improvements.

**Comment by trendschau** [comment]
The buttons are positioned better now in Version 2. I will keep a confirmation window in mind as an optional feature in future.
