### ISSUE TITLE
Display a page (article) without the navigation panel, header, footer

### ISSUE THREAD

**Issue by dstaviss** [typemill/typemill#308]
I have a question - is it possible with typemill to request a page without without the navigation panel, header or footer (I guess with something like passing a url parameter) - I need sometimes to show help content within an iframe in a different tool...
Thx, David

**Comment by trendschau** [comment]
Hi David, 

I did not check it but it is probably hard because the url-params are not send to the frontend right now. If you can get them in frontend, then you could do some conditionals in twig and skip these elements in the theme. 

Anyway, such a solution does not feel very clean. 

Other option is to write a plugin and return the content as pure html with an API so you can include the content in the 3rd-party application with that api and style it there in your third-party-app. I think that is a cleaner way and avoids iframes. Another option might be to render only the content with a separate template in the plugin and query the url-params there (or add another route-ending like /reduced like in the rss plugin).
