### ISSUE TITLE
Ebook addable without id

### ISSUE THREAD

**Issue by MysterieDev** [typemill/typemill#317]
In the plugin ebooksproduct - it is possible to add an ebookproduct without providing an id. This way, the yaml will have an empty string as an id. 

The validator also throws no error, if the id already exists, but at least does not add another entry to the list.
![image](https://user-images.githubusercontent.com/32373099/157044532-95fcce9e-cafc-43b1-a2d5-11e40f46150a.png)

**Comment by trendschau** [comment]
thank you, I fixed both issues (empty id and existing id) with frontend validation, just published it. 

There is no real backend validation right now, which is a task for the next release. I think it is lower prio because an admin would not try to surpase frontend validation and ruin the feature. But best practice would be a proper backend validation for sure...
