### ISSUE TITLE
Git mirroring

### ISSUE THREAD

**Issue by matbgn** [typemill/typemill#339]
Hi,

What would be your approach to map the content (at least MDs) folder with a distant Git forge as backup solution and time machine?

Of course it could be handled with a plugin or at the very least with a crontab but what's your preference by design? And what will be the macro steps you'll advise?

**Comment by trendschau** [comment]
There is pretty much request for a git sync. I did not go deep into it but for now I see two options: 

## Manually per page or pagetree

You could simply create a new tab with a plugin and there you could handle the git sync separately in you plugin, for example a button with "fetch from git" and "post to git". The tab interface is a vue application, details described in the [documentation](https://typemill.net/forms/meta-tabs). The data-handling would be done in php, you can get the markdown and yaml-files with the "item"-element (it has the absolute path to the files) and simply post or sync them with github api. It would also be possible to do this for a whole pagetree because the item element includes the sub-pages too. 

## Automatically with event listeners

You could also sync it automatically with a plugin when you listen to events like onMarkdownLoaded, onMetaLoaded, onPagePublished, onPageDeleted and so on, see [documentation](https://typemill.net/plugin-developers/event-overview). Changes would be stored in typemill repository and in github at the same time without the need to press any additional button. 

## Choose repository

This is an idea from @azettl but not possible right now (should be implemented in Typmill V2): It would be great to wrap the whole "write-"methods in the model-folder somehow, so that you can overwrite the methods and store everything into another repository. This way you could also use databases, github or somehting else. 

Maybe there are even more options, but I have to check it deeper.
