### ISSUE TITLE
search on the roadmap?

### ISSUE THREAD

**Issue by persianphilosopher** [typemill/typemill#5]
Really great stuff. Thank you. It's really close to my ideal.  I hope that some search function would be on the roadmap.
Thank you again

**Comment by trendschau** [comment]
It is now :)

**Comment by persianphilosopher** [comment]
Much appreciated!

**Comment by trendschau** [comment]
I won't implement a search feature in near future, because it's pretty complex and there is an administration board on the roadmap now.

Most of the static JAMStack-people use external services like algolia for search (check it on smashingmagazine), so I suggest to use such a service til the search is on the roadmap again. I just introduced plugins and search is a good candidate for a plugin in future.

**Comment by trendschau** [comment]
Typemill ships with a search-plugin in version 1.2.16 so I close this ticket.
