### ISSUE TITLE
Language Settings

### ISSUE THREAD

**Issue by LiohMoeller** [typemill/typemill#50]
I have tried to change the Language in the settings e.g. to German or French without any noticeable effect. Neither backend nor parts of the frontend (like the search input box) are translated.

**Comment by carstenwm** [comment]
Sebastian, do you want help to translate your system?

**Comment by trendschau** [comment]
Heyho, the language setting does only set the HTML lang-attribute right now, it has no other effects. For frontend I don't think that translations are required because you can edit the whole content. 

For author-ui, translations are planned and help is very welcome (I can only translate into german). But for switching language in ui I have to prepare and enhance the system (several days of work). For now this is low prio for me because the roadmap is packed with month of work already .... https://github.com/typemill/typemill/issues/35

**Comment by trendschau** [comment]
good news, this has been contributed and finished by @iusvar and it is added to version 1.3.1 already!
