### ISSUE TITLE
apostrophe in main menu

### ISSUE THREAD

**Issue by oliviercrouzet** [typemill/typemill#70]
Hello Sebastian,
I am very interested in your work on Typemill, specially with a view to shared documentation aimed at non technie users. I really think Typemill diserves to find its way in cms field. Unfortunately, as a french user I fall upon a heavy issue about apostrophe in menu :
apostrophe is not allowed for file and folder name in the menu. As it's very common to have an apostrophe in a french title, that makes the use of Typemill very restrictive not to say impossible. I suppose the problem is likely to arise for other languages.
About dealing with accent in general terms, I saw that files name are created in the server from the menu input form (after replacing spaces by hyphen) and accents are kept.
May be I'm wrong, but I fear problems to come when dealing with github. I saw that you are actively developping Typemill these days and I am aware that it could be another lot of work, but wouldn't it be better to do a kind of mapping (like in other documentation generator) to separate the name of the file and the title displayed in menu (maybe using yaml meta file).
Anyway, Typemill looks promising and I hope you will be able to find a solution in the near future versions.

Olivier

**Comment by trendschau** [comment]
Hello Olivier, 

thank you for your kind words! You are right, the navigation naming and file naming are combined from historical reason and this is not optimal in all situations. However, we are not so far away from what you say, because with release 1.3.2 you can rename the navigation in the meta-tab (yaml) without any restrictions (only html-chars not allowed) already. In the next steps it would be possible to separate the navigation naming and the file naming when you create a new page in the navigation initially and use the slug for the file-name. It is also planned to make the navigation itself editable. 

Some steps are required, but it is definately in the scope of the next 3 to 5 releases ...

I hope you enjoy Typemill

Sebastian

**Comment by trendschau** [comment]
completely optimized it for the next release, so that navigation title is separated from navigation slug and accepts all characters.

**Comment by trendschau** [comment]
Hi Olivier, 

I published the changes today with version 1.3.3. All french characters should be possible now. Please feel free to update and test.
